language: node_js
node_js:
- '7'
- '6'
sudo: false
deploy:
  provider: npm
  email: stein@hustad.com
  api_key:
    secure: 0ejYhAwgZa8FRLosJiCUwWfAPMke4sNg95wv7DieyXrniwa7VicKFqMEqr7bqBECi19GFeLKB6rQyRM/Aa4pUN2kXa2gWGfWNU82tN/dmp1bw65qJ63PaGtFoxIeJhWA6lIdnBa7YvcfK1DnkNr4EoH7Dyh1tlXteso4G1eQ9wC30K039k/eIQ4gx6SFhfeTNrhsSJgrzSqMjeEMAafSK5c1CKUp6ZeI3vxE2EJmbGlkxtxf+BjSw+YMmMx+MsYEBbZr76EfL+PajCh/HSvL4tsvAIa9dqv4MWJudkQCilzeJPjbUhw76JCxnGtI5XBpHYderXRuyVGsbFaKrHaXzmuf5MiURY/Dwq8weiXLZVPWytkz92uIxOAYZWLqiunv8bep2ob3v8TFk+F72xINWFLO6Jt6Fh+17jJdfrOF0/uVqE22i7UMFZ5TsVgulLPG9shlr0Gh2XwPXZGEgY7ZR1X3QvIeeeADfD3NVcwAOJoM/lIJHQA39b6FXV0ngw3zYIZr/BxQv1zjyQRDAZVkahJb/b7wTcvzD6CHAwCeqIJL/Fd5lbRJoLlMbf3RjOylzlHpu1RXlm3zwpM5aCKYSOd6tF4p7mPOojpmx+O6hVNTQxBg/en3beN8XLpzIvfenWseN6pwxciI4d5zfxStr3kvhw5WmR/dg2thQiugrcw=
  on:
    tags: true
    repo: smh/mocha-githook-reporter
